advocate_europe/urls.py
from allauth import urls as allauth_urls
from ckeditor_uploader import views as ck_views
from django.conf import settings
from django.conf.urls import i18n, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.views.generic import TemplateView
from django.views.i18n import JavaScriptCatalog
from rest_framework import routers
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.contrib.sitemaps import views as wagtail_sitemap_views
from wagtail.contrib.sitemaps.sitemap_generator import \
    Sitemap as WagtailSitemap
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from adhocracy4.api import routers as a4routers
from adhocracy4.comments.api import CommentViewSet
from adhocracy4.ratings.api import RatingViewSet
from adhocracy4.reports.api import ReportViewSet
from apps.contrib.sitemaps.adhocracy4_sitemap import Adhocracy4Sitemap
from apps.contrib.sitemaps.static_sitemap import StaticSitemap
from apps.follows.api import FollowViewSet
from apps.ideas import urls as idea_urls
from apps.invites import urls as invite_urls
from apps.journeys import urls as journey_urls
from apps.users import urls as user_urls

js_info_dict = {
    'packages': ('adhocracy4.comments',),
}

router = routers.DefaultRouter()
router.register(r'reports', ReportViewSet, basename='reports')
router.register(r'follows', FollowViewSet, basename='follows')

ct_router = a4routers.ContentTypeDefaultRouter()
ct_router.register(r'comments', CommentViewSet, basename='comments')
ct_router.register(r'ratings', RatingViewSet, basename='ratings')

sitemaps = {
    'adhocracy4': Adhocracy4Sitemap,
    'wagtail': WagtailSitemap,
    'static': StaticSitemap
}

urlpatterns = [
    url(r'^django-admin/', admin.site.urls),
    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
    url(r'^api/', include(router.urls)),
    url(r'^api/', include(ct_router.urls)),
    url(r'^upload/',
        login_required(ck_views.upload), name='ckeditor_upload'),
    url(r'^browse/',
        never_cache(login_required(ck_views.browse)), name='ckeditor_browse'),
]

urlpatterns += [
    url(r'^accounts/', include(allauth_urls)),
    url(r'', include(user_urls)),
    url(r'^ideas/', include(idea_urls)),
    url(r'^invites/', include(invite_urls)),
    url(r'^journeys/', include(journey_urls)),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^i18n/', include(i18n)),

    url(r'^sitemap\.xml$', wagtail_sitemap_views.index,
        {'sitemaps': sitemaps, 'sitemap_url_name': 'sitemaps'}),
    url(r'^sitemap-(?P<section>.+)\.xml$', wagtail_sitemap_views.sitemap,
        {'sitemaps': sitemaps}, name='sitemaps'),
    url(r'^robots\.txt$', TemplateView.as_view(
        template_name='robots.txt',
        content_type="text/plain"), name="robots_file"),

    url(r'', include(wagtail_urls))
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    import debug_toolbar

    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/ideas/urls.py
from django.conf.urls import url

from . import views
from .forms import (ApplicantSectionForm, CommunitySectionForm,
                    FinanceAndDurationSectionForm, FinishForm,
                    IdeaChallengeCampSectionForm, IdeaSectionForm,
                    ImpactSectionForm, NetworkForm, PartnersSectionForm,
                    SelectionCriteriaSectionForm)

urlpatterns = [
    url(r'create/module/(?P<slug>[-\w_]+)/$',
        views.IdeaSketchCreateWizard.as_view(
            [ApplicantSectionForm, PartnersSectionForm,
             IdeaSectionForm, ImpactSectionForm,
             IdeaChallengeCampSectionForm,
             CommunitySectionForm, FinishForm]), name='idea-sketch-create'),
    url(r'^archived/(?P<slug>[-\w_]+)/$',
        views.IdeaSketchArchivedDetailView.as_view(),
        name='idea-sketch-archived-detail'),
    url(r'^(?P<slug>[-\w_]+)/$',
        views.IdeaDetailView.as_view(), name='idea-detail'),
    url(r'^(?P<slug>[-\w_]+)/edit/$',
        views.IdeaSketchEditView.as_view(), name='idea-sketch-update'),
    url(r'^(?P<slug>[-\w_]+)/edit/(?P<form_number>[\d]+)/$',
        views.IdeaSketchEditView.as_view(), name='idea-sketch-update-form'),
    url(r'^(?P<slug>[-\w_]+)/proposal/$',
        views.ProposalCreateWizard.as_view(
            [ApplicantSectionForm, PartnersSectionForm,
             IdeaSectionForm, ImpactSectionForm, SelectionCriteriaSectionForm,
             NetworkForm, FinanceAndDurationSectionForm,
             CommunitySectionForm, FinishForm]
        ), name='idea-sketch-add-proposal'),
    url(r'^(?P<slug>[-\w_]+)/proposal/edit/$',
        views.ProposalEditView.as_view(), name='proposal-update'),
    url(r'^(?P<slug>[-\w_]+)/proposal/edit/(?P<form_number>[\d]+)/$',
        views.ProposalEditView.as_view(), name='proposal-update-form'),
    url(r'list/export/$', views.IdeaExportView.as_view(),
        name='idea-export'),
    url(r'^$',
        views.IdeaListView.as_view(), name='idea-sketch-list')

]

apps/journeys/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import ugettext as _

from adhocracy4 import transforms
from apps.ideas.models import Idea

TEXT_HELPTEXT = _("To add content from Vimeo, "
                  "Youtube, Facebook, flickr, "
                  "soundcloud or instagram "
                  "just paste the url "
                  "into the text.")


class JourneyEntry(models.Model):
    IMPACT_ROAD = 'ir'
    HEROINES = 'he'
    IMPACT_STORY = 'is'
    IDEA = 'id'
    SUCCESS = 'su'
    FAILING = 'fa'
    JOIN = 'jo'
    ANYTHING = 'an'
    CATEGORY_CHOICES = (
        (IMPACT_ROAD, _('Road to impact')),
        (HEROINES, _('Heroines and heroes')),
        (IMPACT_STORY, _('Impact Story')),
        (IDEA, _('Take this idea!')),
        (SUCCESS, _('Success')),
        (FAILING, _('Failing forward')),
        (JOIN, _('Join forces!')),
        (ANYTHING, _('Anything else?'))
    )

    created = models.DateTimeField(editable=True, default=timezone.now)
    modified = models.DateTimeField(blank=True, null=True, editable=True)

    creator = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)

    idea = models.ForeignKey(Idea, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    category = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES
    )
    text = RichTextUploadingField(config_name='image-editor',
                                  help_text=TEXT_HELPTEXT)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('idea-detail', args=[self.idea.slug])

    def save(self, *args, **kwargs):
        if self.pk is not None:
            self.modified = timezone.now()
        self.text = transforms.clean_html_field(
            self.text,
            setting='image-editor')
        super().save(*args, **kwargs)

    @property
    def project(self):
        return self.idea.project

apps/ideas/views.py
import os
from datetime import datetime

from django.conf import settings
from django.contrib.messages.views import SuccessMessageMixin
from django.core.files.base import ContentFile
from django.core.files.storage import FileSystemStorage
from django.forms.models import model_to_dict
from django.shortcuts import redirect
from django.utils.translation import ugettext as _
from django.views import generic
from formtools.wizard.views import SessionWizardView
from pytz import timezone
from rules.contrib.views import PermissionRequiredMixin

from adhocracy4.exports import mixins as export_mixins
from adhocracy4.exports import views as export_views
from adhocracy4.filters import views as filter_views
from adhocracy4.phases.models import Phase
from apps.wizards import mixins as wizard_mixins

from . import filters, forms, mixins
from .models import Idea, IdeaSketch, IdeaSketchArchived, Proposal


class IdeaExportView(PermissionRequiredMixin,

                     export_views.BaseExport,
                     export_mixins.ItemExportWithLinkMixin,
                     mixins.ExportMultiModelIdeaFieldsMixin,
                     export_mixins.ItemExportWithRatesMixin,
                     export_mixins.ItemExportWithCommentCountMixin,
                     export_mixins.ItemExportWithCommentsMixin,

                     # Both AbstractXlsxExportView and FilteredListView
                     # define `get()`. To ensure data is exported, the
                     # AbstractXlsxExportView class has to be defined first.
                     export_views.AbstractXlsxExportView,
                     filter_views.FilteredListView,
                     ):

    permission_required = 'advocate_europe_ideas.export_idea'
    model = Idea
    filter_set = filters.IdeaFilterSet
    exclude = ['module', 'item_ptr', 'slug', 'idea_ptr',
               'idea_image', 'idea_sketch_archived']

    def get_base_filename(self):
        settings_time_zone = timezone(settings.TIME_ZONE)
        return 'download_%s' % (
            datetime.now(settings_time_zone).strftime('%Y%m%dT%H%M%S'))

    def get_queryset(self):
        queryset = super().get_queryset()\
            .annotate_comment_count()\
            .annotate_positive_rating_count()
        return queryset

    def get_object_list(self):
        return (idea.proposal if hasattr(idea, 'proposal') else idea.ideasketch
                for idea in self.get_queryset())

    @property
    def raise_exception(self):
        return self.request.user.is_authenticated

    def get_comment_count_data(self, item):
        item = item.idea
        return super().get_comment_count_data(item)

    def get_comments_data(self, item):
        item = item.idea
        return super().get_comments_data(item)

    def get_ratings_positive_data(self, item):
        item = item.idea
        return super().get_ratings_positive_data(item)

    def get_creator_data(self, item):
        return item.creator.email

    def get_created_data(self, item):
        return item.created.isoformat()

    def get_co_workers_data(self, item):
        co_workers = ', '.join(
            [co_worker.email for co_worker in item.idea.co_workers.all()]
        )
        return co_workers


class IdeaSketchCreateWizard(PermissionRequiredMixin,
                             mixins.ModuleMixin,
                             wizard_mixins.CustomWizardMixin,
                             SessionWizardView):
    permission_required = 'advocate_europe_ideas.add_ideasketch'
    file_storage = FileSystemStorage(
        location=os.path.join(settings.MEDIA_ROOT, 'idea_sketch_images'))
    title = _('Idea Sketch')
    finish_section_text = _('As soon as you have submitted your application, '
                            'it will be published online in the idea space.')
    finish_section_btn = _('Submit your idea')

    @property
    def end_date(self):
        if (self.module.active_phase and
                self.module.active_phase.has_feature('crud', IdeaSketch)):
            settings_time_zone = timezone(settings.TIME_ZONE)
            end_date = self.module.active_phase.end_date
            return end_date.astimezone(settings_time_zone)\
                .strftime("%d %B %Y (%H:%M CET)")

    def get_form_kwargs(self, step=None):
        if step == '0':
            return {'end_date': self.end_date}
        if step == '5':
            return {'display_idea_challenge_camp_checkbox': True}
        return {}

    def done(self, form_list, **kwargs):
        special_fields = ['accept_conditions', 'co_workers_emails',
                          'confirm_publicity', 'confirm_idea_challenge_camp']

        data = self.get_all_cleaned_data()
        idea_sketch = IdeaSketch.objects.create(
            creator=self.request.user,
            module=self.module,
            **{
                field: value for field, value in data.items()
                if field not in special_fields
            }
        )

        for name, email in data['co_workers_emails']:
            idea_sketch.ideainvite_set.invite(
                self.request.user,
                email
            )

        return redirect(idea_sketch.get_absolute_url())

    @property
    def raise_exception(self):
        return self.request.user.is_authenticated


class IdeaSketchEditView(
    PermissionRequiredMixin,
    mixins.MultiFormEditMixin,
    SuccessMessageMixin,
    generic.UpdateView
):
    permission_required = 'advocate_europe_ideas.change_idea'
    model = IdeaSketch
    template_name = 'advocate_europe_ideas/idea_update_form.html'
    success_message = _('Idea Sketch saved')
    next_view = 'idea-sketch-update-form'
    title = _('Update Idea Sketch')

    form_classes = [
        forms.ApplicantSectionForm,
        forms.PartnersSectionForm,
        forms.IdeaSectionForm,
        forms.ImpactSectionForm,
        forms.IdeaChallengeCampSectionForm,
        forms.CommunitySectionEditForm,
    ]

    @property
    def raise_exception(self):
        return self.request.user.is_authenticated


class IdeaDetailView(generic.DetailView):
    display_type = 'idea'
    model = Idea
    queryset = Idea.objects.annotate_positive_rating_count()

    @property
    def idea_dict(self):
        return model_to_dict(self.object)

    def get_context_data(self, **kwargs):
        idea_list_1 = []
        idea_list_2 = []
        budget_list = []
        idea_list_1.append((_('Idea pitch'), self.object.idea_pitch))
        if self.object.idea_location_specify:
            idea_list_1.append((_('Where will your idea take place?'),
                                self.object.idea_location_specify))
        idea_list_1.append((_('Why does Europe need your idea?'),
                            self.object.challenge))
        idea_list_1.append((_('What is your impact?'), self.object.outcome))
        idea_list_1.append((_('How do you get there?'), self.object.plan))
        idea_list_1.append((_('What is your story?'), self.object.importance))
        idea_list_1.append((_('Who are you doing it for?'),
                            self.object.target_group))

        if hasattr(self.object, 'proposal') and self.object.proposal:
            idea_list_1.append((_('What makes your idea stand apart?'),
                                self.object.proposal.selection_apart))
            idea_list_2.append((_('Major expenses'),
                                self.object.proposal.major_expenses))

        if self.object.reach_out:
            idea_list_2.append((_('What do you need from the Advocate Europe '
                                'community?'), self.object.reach_out))

        if hasattr(self.object, 'proposal') and self.object.proposal:
            budget_list.append((_('Funding requested from Advocate Europe'),
                                self.object.proposal.budget_requested))
            budget_list.append((_('Total budget'),
                                self.object.proposal.total_budget))
            if self.object.budget_granted:
                budget_list.append((_('Funding granted from Advocate Europe'),
                                    self.object.proposal.budget_granted))

        partner_list = []
        if (self.object.partner_organisation_1_name
                or self.object.partner_organisation_1_website):
            partner_list.append((self.object.partner_organisation_1_name,
                                 self.object.partner_organisation_1_website,
                                 self.object.
                                 get_partner_organisation_1_country_display))
        if (self.object.partner_organisation_2_name
                or self.object.partner_organisation_2_website):
            partner_list.append((self.object.partner_organisation_2_name,
                                 self.object.partner_organisation_2_website,
                                 self.object.
                                 get_partner_organisation_2_country_display))
        if (self.object.partner_organisation_3_name
                or self.object.partner_organisation_3_website):
            partner_list.append((self.object.partner_organisation_3_name,
                                 self.object.partner_organisation_3_website,
                                 self.object.
                                 get_partner_organisation_3_country_display))

        context = super().get_context_data(**kwargs)
        context['idea_list_1'] = idea_list_1
        context['idea_list_2'] = idea_list_2
        context['budget_list'] = budget_list
        context['partner_list'] = partner_list
        return context


class IdeaSketchArchivedDetailView(IdeaDetailView):
    display_type = 'idea_sketch_archive'
    model = IdeaSketchArchived
    template_name = 'advocate_europe_ideas/idea_detail.html'
    context_object_name = 'idea'
    slug_field = 'idea__slug'
    queryset = IdeaSketchArchived.objects.all()


class ProposalCreateWizard(PermissionRequiredMixin,

apps/ideas/templates/advocate_europe_ideas/idea_detail.html
{% extends "base.html" %}

{% load i18n react_comments rules static force_translation idea_tags absolute_url rules %}

{% block title %} {{ idea.idea_title }} {% endblock %}

{% block social_meta %}

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Advocate Europe | {{ idea.idea_title }}">
    <meta name="twitter:description" content="{{ idea.idea_pitch }}">
    {% if idea.idea_image %}
        <meta name="twitter:image" content="{% get_absolute_uri obj=idea.idea_image.url %}">
    {% else %}
        <meta name="twitter:image" content="{% get_absolute_uri_static obj='images/logo_01.png' %}">
    {% endif %}


    <meta property="og:url" content="{{ request.build_absolute_uri }}">
    <meta property="og:title" content="Advocate Europe | {{ idea.idea_title }}">
    <meta property="og:description" content="{{ idea.idea_pitch }}">
    {% if idea.idea_image %}
        <meta property="og:image" content="{% get_absolute_uri obj=idea.idea_image.url %}">
        <meta property="og:image:width" content="{{ idea.idea_image.width }}">
        <meta property="og:image:height" content="{{ idea.idea_image.height }}">
    {% else %}
        <meta property="og:image" content="{% get_absolute_uri_static obj='images/logo_01.png' %}">
        <meta property="og:image:width" content="360">
        <meta property="og:image:height" content="129">
    {% endif %}

{% endblock %}

{% block content %}
    {% force_translation 'en' %}
    <div class="ideadetail">
        <div class="container">

            {% include 'advocate_europe_ideas/includes/idea_detail_header.html' %}

            <div class="row hidden-lg hidden-md hidden-sm ideadetail-xs-support">
                <ul class="nav">
                    {% if view.display_type == 'idea' %}
                    <li class="nav-idea nav-support">
                        {% has_perm 'advocate_europe_ideas.may_rate_idea' request.user idea as may_rate_idea %}
                        {% if may_rate_idea and view.display_type == 'idea' %}
                        {% react_supports idea True %}
                        {% endif %}
                    </li>
                    {% endif %}
                    {% include 'advocate_europe_ideas/includes/idea_detail_watch_btns.html' with xs_class="" spacing="<br>" %}
                </ul>
            </div>

            <div class="row ideadetail-tab-bar">
                <ul class="nav navbar-nav nav-tabs tabs" role="tablist">

                    <li role="presentation" class="nav-item">
                        <a href="#info" class="nav-link" aria-controls="info" role="tab" data-toggle="tab">{% trans "Creators" %}</a>
                    </li>

                    <li role="presentation" class="nav-item {% if not idea.proposal or not idea.is_winner or idea.journeyentry_set.all.count == 0 %}active{% endif %}">
                        <a href="#idea" class="nav-link" aria-controls="idea" role="tab" data-toggle="tab">{% trans "Idea" %}</a>
                    </li>

                    {% if idea.is_winner %}
                        <li role="presentation" class="nav-item {% if idea.proposal and idea.is_winner and idea.journeyentry_set.all.count > 0 %}active{% endif %}">
                            <a href="#journey" class="nav-link" aria-controls="idea" role="tab" data-toggle="tab">{% trans "Project Journey" %}</a>
                        </li>
                    {% endif %}

                    {% include 'advocate_europe_ideas/includes/idea_detail_watch_btns.html' with xs_class="hidden-xs" %}
                </ul>
            </div>

            <div class="row tab-content ideadetail-content">
                <div role="tabpanel" class="col-md-offset-1 col-md-7 col-sm-8 col-xs-12 tab-pane" id="info">
                    {% include 'advocate_europe_ideas/includes/idea_detail_tab_info.html' %}
                </div>
                <div role="tabpanel" class="col-md-offset-1 col-md-7 col-sm-8 col-xs-12 tab-pane  {% if not idea.proposal or not idea.is_winner or idea.journeyentry_set.all.count == 0 %} active {% endif %}" id="idea">
                    {% include 'advocate_europe_ideas/includes/idea_detail_tab_idea.html' %}
                </div>
                {% if idea.is_winner %}
                    <div role="tabpanel" class="col-md-offset-1 col-md-7 col-sm-8 col-xs-12 tab-pane {% if idea.proposal and idea.is_winner and idea.journeyentry_set.all.count > 0 %} active {% endif %}" id="journey">
                        {% include 'advocate_europe_ideas/includes/idea_detail_tab_journey.html' %}
                    </div>
                {% endif %}

                <div class="col-md-3 col-sm-4 col-xs-12 ideadetail-info-boxes">

                    {% if idea.proposal and idea.jury_statement %}
                        <div class="ideadetail-info-box jurystatement">
                            <h4><i class="fa fa-trophy" aria-hidden="true"></i> {% trans 'Why this idea?' %}</h4>
                            <p>{{ idea.jury_statement }}</p>
                        </div>
                    {% endif %}


                    <div class="ideadetail-info-box">
                        <h4>{% trans 'Team' %}</h4>
                        <p>
                            <span class="avatar-round-small" style="background-image: url({{ idea.creator.avatar_or_fallback_url }})"></span>
                            <span class="co-worker">
                                <a href="{% url 'profile' idea.creator.username %}">{{ idea.creator.username }}</a>
                            </span>
                        </p>
                        {% for co_worker in idea.co_workers.all %}
                            {% if co_worker.username != idea.creator.username %}
                            <p class="ideadetail-info-box-co-workers">
                                <span class="avatar-round-small no-decoration" style="background-image: url({{ co_worker.avatar_or_fallback_url }})"></span>
                                <span class="co-worker">
                                    <a href="{% url 'profile' co_worker.username %}">{{ co_worker.username }}</a>
                                </span>
                            </p>
                            {% endif %}
                        {% endfor %}
                        <div class="idea-dates">
                            {% trans 'Idea created on' %} {{ idea.created|date }}
                        </div>
                        {% if idea.modified %}
                        <div class="idea-dates">
                            {% trans 'Last edit on' %} {{ idea.modified|date }}
                        </div>
                        {% endif %}
                    </div>

                </div>
            </div>
            {% if view.display_type == 'idea' %}
                <div class="container-medium ideadetail-comments">
                    <h4 class="ideadetail-comments-title">{% trans "Write comment" %}</h4>
                    {% react_comments idea %}
                </div>
            {% endif %}
        </div>
    </div>
 {% endforce_translation %}
{% endblock %}

apps/ideas/templates/advocate_europe_ideas/idea_list.html
{% extends "base.html" %}

{% load i18n rules idea_tags force_translation %}

{% block title %} {% trans 'All ideas' %} {% endblock %}

{% block content %}
    {% force_translation 'en' %}
    <div class="custompage-blue">
        <div class="container">
            <header class="custompage-header">
                <h1>{% trans "All ideas" %}</h1>
                <p>
                    {% if view.active_phase %}
                        {{ view.active_phase.description }}
                    {% else %}
                        {% trans "Ideas from past idea challenges" %}
                    {% endif %}
                </p>
            </header>
        </div>
    </div>
    <div class="custompage-45">
        <div class="container">
            <div class="row equal idealist-content">
                <div class="col-md-3 col-sm-3 col-xs-12 idealist-controls">
                    <div class="filter-bar idealist-filter clearfix">
                        <div class="hidden-xs">
                            {% for field in view.filter.form %}
                                <div class="row">
                                    <div class="col-lg-12 filter-{{ field.name }}">
                                        {{ field }}
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="hidden-sm hidden-md hidden-lg mobile-filter">
                            <button class="btn btn-default btn-collapse collapsed" type="button"
                                    data-toggle="collapse" data-target="#filter" aria-expanded="false"
                                    aria-controls="Filter">
                                <div class="btn-label">
                                    {% trans "Filters" %}
                                    {% count_active_filter view.filter.data as filter_count %}
                                    {% if filter_count > 0 %}
                                        <span class="number-of-filters">
                                    {{ filter_count }}
                                </span>
                                    {% endif %}
                                </div>
                                <i class="fa fa-chevron-up"></i>
                            </button>
                            <div class="collapse" id="filter">
                                <div class="card card-block">
                                    {% for field in view.filter.form %}
                                        {{ field }}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% has_perm 'advocate_europe_ideas.export_idea' request.user as can_export %}
                    {% if can_export %}
                        <a class="btn btn-ae-secondary export-btn btn-wide" href="
                                {% url 'idea-export' %}{{ '?'|add:view.filter.data.urlencode }}">{% trans "export" %}</a>
                    {% endif %}
                </div>
                <div class="col-md-9 col-sm-9 col-xs-12 idealist-list-container">
                    {% if not idea_list %}
                    <div class="idealist-no-entry">
                        <h4>{% trans "Sorry, no ideas exist for the chosen filters." %}</h4>
                    </div>
                    {% endif %}
                    <div class="idealist-list">
                        {% if page_obj.number == 1 and view.is_cta_enabled %}
                        <div class="idealist-itemwrapper">
                            {% include 'advocate_europe_ideas/includes/call_to_action_tile.html' with module=view.cta_object %}
                        </div>
                        {% endif %}
                        {% for idea in idea_list %}
                        <div class="idealist-itemwrapper">
                            {% include 'advocate_europe_ideas/includes/idealist_item.html' %}
                        </div>
                        {% endfor %}
                    </div>
                    {% if is_paginated %}
                    {% include 'includes/pagination.html' %}
                    {% endif %}
                    <div class="idealist-found {% if not is_paginated %}margin{% endif %}">
                    {% if idea_list %}
                    {% blocktrans count ideacount=view.get_queryset.count %}
                        <p>One idea found</p>
                        {% plural %}
                        <p>{{ ideacount }} Ideas found</p>
                    {% endblocktrans %}
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>



    {% endforce_translation %}
{% endblock %}

apps/ideas/templates/advocate_europe_ideas/ideasketch_detail_tab_idea.html
{% load i18n static %}

<div class="ideadetail-tab">
    <div class="ideadetailtab-header">
        <h2>{% trans "Idea" %}</h2>
    </div>
    {% for field in idea_list %}
        <div class="ideadetailtab-con-header">
            <h4>{{ field.0 }}</h4>
        </div>
        <div class="ideadetailtab-con-text">
            <p>{{ field.1 }}</p>
        </div>
    {% endfor %}
</div>

apps/ideas/templates/advocate_europe_ideas/ideasketch_detail_tab_info.html
{% load i18n static %}

<div class="ideadetail-tab">
    <div class="ideadetailtab-header">
        <h2>{% trans "Creators" %}</h2>
    </div>
    <div class="ideadetailtab-con-header">
        <h4>{% trans "Who is behind this?" %}</h4>
    </div>
    <div class="ideadetailtab-con-text">
        <p class="ideadetailtab-bold-name">
        {{ ideasketch.first_name }}
        {{ ideasketch.last_name }}
        </p>
        <p>
        {{ ideasketch.organisation_name }}
        </p>
        <p><a target="_blank" href="{{ ideasketch.organisation_website }}">
        {{ ideasketch.organisation_website }}
        </a></p>
        <p>
        {{ ideasketch.get_organisation_country_display }}
        </p>
    </div>
    {% if partner_list %}
        <div class="ideadetailtab-con-header">
            <h4>{% trans "Who is joining forces?" %}</h4>
        </div>
        <div class="ideadetailtab-con-text">
            {% for field in partner_list %}
                <p class="ideadetailtab-bold-name">
                    {{ field.0 }}
                </p>
                <a href="{{ field.1 }}"><p>{{ field.1 }}</p></a>
                <p>{{ field.2 }}</p>
                <br>
            {% endfor %}
            <p>{{ ideasketch.partners_more_info }}</p>
        </div>
    {% endif %}
</div>